baseURL = "http://ines-almeida.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en-us"
# theme = "vncnt-hugo"
theme = "almeida"
title = "Inês Almeida"

[permalinks]
  fixed = ":title/"

[params]
  author = "Inês Almeida"
  email = "ineesalmeida@gmail.com"
  avatar = "img/me.jpg"
  favicon = "img/myfavicon.ico"
  sections = ["hero", "about", "experience", "education", "projects", "contact"]

[params.contact]
  github = "https://github.com/ineesalmeida"
  instagram = "https://www.instagram.com/inees_almeida/"
  linkedin = "https://www.linkedin.com/in/ines-de-almeida/"

[params.color]
  primary = "royalblur"
  secondary = "coral"
  light = "aliceblue"
  dark = "#333"
